title: "圏論勉強ノート"
summary: |-
  圏論を勉強したメモ書きです。
  勉強を進めるにつれてページが増えていきます。

  数学的な厳密さを欠いた議論や証明を省いた部分が多くあるので、これを使って勉強するのはおすすめしません。

  教科書はSteve AwodeyのCategory Theoryを使っています。
  集合論の教科書として松坂和夫先生の集合・位相入門を使っています。

topics:
  - "haskell"
  - "圏論"
published: true
price: 0
toc_depth: 2
allow_override: true
chapters:
  - "category"
  - examples-of-categories
  - "discrete-categories"
  - "largeness-of-categories"
  - "commutative-diagram"
  - "isomorphism"
  - "opposite-categories"
  - "functor"
  - "natural-transformation"
  - "natural-isomorphism"
  - "vertical-composition"
  - "horizontal-composition"
  - "identity_natural_transformation"
  - "equivalence-of-categories"
  - adjunction-unit-counit
  - universal-mapping-property
  - product
  - diagram-and-index-category
  - category-of-functors
  - constant-functors
  - elevation
  - limit
  - pullback
  - monic-and-epic-morphisms
  - equaliser
  - coequaliser
  - complete
  - adjunction-ump
  - opposite-functors
  - category-of-small-categories
  - comma-category
  - variants-of-comma-category
  - slice-category
  - hom-functor
  - theorems-on-hom-functors
  - adjunction-hom-functor
  - adjunction-allows-to-commute-categories
  - full-and-faithful-functors
  - representable-functor
  - collection-of-natural-transformations
  - set-valued-functor
  - yoneda-lemma
  - yoneda-embedding
  - product-category
  - bifunctor
  - monoidal-category
  - monad
  - adjunctions-derive-monads
  - forgetful-functors
  - free-functors
  - initial-objects
  - f-algebra
  - catamorphism
  - kan-extension
  - dinatural-transformation
  - end
